In [1]:
import tpot
print(tpot.__version__)

c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\tpot\builtins\__init__.py:36: UserWarning: Warning: optional dependency `torch` is not available. - skipping import of NN models.
  warnings.warn("Warning: optional dependency `torch` is not available. - skipping import of NN models.")

0.12.2

In [2]:
from src.tpot_experiments import run_tpot_experiment

test_result = run_tpot_experiment(
    dataset_name="breast_cancer",
    seed=42,
)

test_result

Running TPOT: breast_cancer | seed 42

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9811844295188893

Generation 2 - Current best internal CV score: 0.9812635111075929

Generation 3 - Current best internal CV score: 0.9812635111075929

Generation 4 - Current best internal CV score: 0.9836031442454629

Generation 5 - Current best internal CV score: 0.9836031442454629

Generation 6 - Current best internal CV score: 0.9836054105755505

Generation 7 - Current best internal CV score: 0.9836054105755505

10.17 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: MLPClassifier(MLPClassifier(input_matrix, alpha=0.01, learning_rate_init=1.0), alpha=0.001, learning_rate_init=0.01)
Best pipeline: Pipeline(steps=[('stackingestimator',
                 StackingEstimator(estimator=MLPClassifier(alpha=0.01,
                                                           learning_rate_init=1.0,
                                                           random_state=42))),
                ('mlpclassifier',
                 MLPClassifier(alpha=0.001, learning_rate_init=0.01,
                               random_state=42))])
Test Macro F1: 0.9623
Search runtime: 611.26 seconds

c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(
c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

{'framework': 'TPOT',
 'dataset': 'breast_cancer',
 'seed': 42,
 'best_model': "Pipeline(steps=[('stackingestimator',\n                 StackingEstimator(estimator=MLPClassifier(alpha=0.01,\n                                                           learning_rate_init=1.0,\n                                                           random_state=42))),\n                ('mlpclassifier',\n                 MLPClassifier(alpha=0.001, learning_rate_init=0.01,\n                               random_state=42))])",
 'accuracy': 0.9649122807017544,
 'precision_macro': 0.9623015873015872,
 'recall_macro': 0.9623015873015872,
 'f1_macro': 0.9623015873015872,
 'search_runtime_seconds': 611.2621540999971,
 'prediction_runtime_seconds': 0.03895449987612665,
 'total_runtime_seconds': 611.3011085998733}

In [3]:
from src.tpot_experiments import run_all_tpot_experiments

tpot_results = run_all_tpot_experiments()

tpot_results

Running TPOT: breast_cancer | seed 42

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9811844295188893

Generation 2 - Current best internal CV score: 0.9812635111075929

Generation 3 - Current best internal CV score: 0.9812635111075929

Generation 4 - Current best internal CV score: 0.9836031442454629

Generation 5 - Current best internal CV score: 0.9836031442454629

Generation 6 - Current best internal CV score: 0.9836054105755505

Generation 7 - Current best internal CV score: 0.9836054105755505

463.39 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: MLPClassifier(MLPClassifier(input_matrix, alpha=0.01, learning_rate_init=1.0), alpha=0.001, learning_rate_init=0.01)

c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(
c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Best pipeline: Pipeline(steps=[('stackingestimator',
                 StackingEstimator(estimator=MLPClassifier(alpha=0.01,
                                                           learning_rate_init=1.0,
                                                           random_state=42))),
                ('mlpclassifier',
                 MLPClassifier(alpha=0.001, learning_rate_init=0.01,
                               random_state=42))])
Test Macro F1: 0.9623
Search runtime: 27812.4 seconds

Running TPOT: breast_cancer | seed 123

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9809495283670137

Generation 2 - Current best internal CV score: 0.9809495283670137

Generation 3 - Current best internal CV score: 0.9809495283670137

Generation 4 - Current best internal CV score: 0.9810124720543392

Generation 5 - Current best internal CV score: 0.9810124720543392

Generation 6 - Current best internal CV score: 0.9810124720543392

Generation 7 - Current best internal CV score: 0.9811263222029073

Generation 8 - Current best internal CV score: 0.9811263222029073

Generation 9 - Current best internal CV score: 0.9833745745851633

Generation 10 - Current best internal CV score: 0.9833745745851633

Generation 11 - Current best internal CV score: 0.9833745745851633

Generation 12 - Current best internal CV score: 0.9833745745851633

10.57 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: SGDClassifier(input_matrix, alpha=0.01, eta0=0.01, fit_intercept=False, l1_ratio=0.0, learning_rate=constant, loss=modified_huber, penalty=elasticnet, power_t=0.5)
Best pipeline: Pipeline(steps=[('sgdclassifier',
                 SGDClassifier(alpha=0.01, eta0=0.01, fit_intercept=False,
                               l1_ratio=0.0, learning_rate='constant',
                               loss='modified_huber', penalty='elasticnet',
                               random_state=123))])
Test Macro F1: 0.9623
Search runtime: 634.36 seconds

Running TPOT: breast_cancer | seed 2026

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9786368899299933

Generation 2 - Current best internal CV score: 0.9786368899299933

Generation 3 - Current best internal CV score: 0.9786368899299933

Generation 4 - Current best internal CV score: 0.9788086223006086

Generation 5 - Current best internal CV score: 0.9788086223006086

Generation 6 - Current best internal CV score: 0.9834861584036437

Generation 7 - Current best internal CV score: 0.9834861584036437

Generation 8 - Current best internal CV score: 0.9834861584036437

Generation 9 - Current best internal CV score: 0.9834861584036437

Generation 10 - Current best internal CV score: 0.9834861584036437

Generation 11 - Current best internal CV score: 0.9834861584036437

Generation 12 - Current best internal CV score: 0.9834861584036437

Generation 13 - Current best internal CV score: 0.9834861584036437

Generation 14 - Current best internal CV score: 0.9835450369294808

Generation 15 - Current best internal CV score: 0.9835630632619463

Generation 16 - Current best internal CV score: 0.9835630632619463

Generation 17 - Current best internal CV score: 0.9835630632619463

Generation 18 - Current best internal CV score: 0.9835790815789671

Generation 19 - Current best internal CV score: 0.9835790815789671

10.06 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: MLPClassifier(MinMaxScaler(input_matrix), alpha=0.001, learning_rate_init=0.1)
Best pipeline: Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                ('mlpclassifier',
                 MLPClassifier(alpha=0.001, learning_rate_init=0.1,
                               random_state=2026))])
Test Macro F1: 0.9349
Search runtime: 604.68 seconds

Running TPOT: wine | seed 42

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.986830674298705

Generation 2 - Current best internal CV score: 0.9926570048309179

Generation 3 - Current best internal CV score: 0.9926570048309179

Generation 4 - Current best internal CV score: 0.9926570048309179

Generation 5 - Current best internal CV score: 0.9926570048309179

Generation 6 - Current best internal CV score: 1.0

Generation 7 - Current best internal CV score: 1.0

Generation 8 - Current best internal CV score: 1.0

Generation 9 - Current best internal CV score: 1.0

Generation 10 - Current best internal CV score: 1.0

Generation 11 - Current best internal CV score: 1.0

Generation 12 - Current best internal CV score: 1.0

Generation 13 - Current best internal CV score: 1.0

Generation 14 - Current best internal CV score: 1.0

Generation 15 - Current best internal CV score: 1.0

Generation 16 - Current best internal CV score: 1.0

Generation 17 - Current best internal CV score: 1.0

Generation 18 - Current best internal CV score: 1.0

10.01 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: GradientBoostingClassifier(LogisticRegression(PolynomialFeatures(input_matrix, degree=2, include_bias=False, interaction_only=False), C=5.0, dual=False, penalty=l2), learning_rate=1.0, max_depth=4, max_features=0.7500000000000001, min_samples_leaf=18, min_samples_split=8, n_estimators=100, subsample=0.9000000000000001)
Best pipeline: Pipeline(steps=[('polynomialfeatures', PolynomialFeatures(include_bias=False)),
                ('stackingestimator',
                 StackingEstimator(estimator=LogisticRegression(C=5.0,
                                                                random_state=42))),
                ('gradientboostingclassifier',
                 GradientBoostingClassifier(learning_rate=1.0, max_depth=4,
                                            max_features=0.7500000000000001,
                                            min_samples_leaf=18,
                                            min_samples_split=8,
                                            random_state=42,
                                            subsample=0.9000000000000001))])
Test Macro F1: 0.971
Search runtime: 601.31 seconds

Running TPOT: wine | seed 123

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9926570048309179

Generation 2 - Current best internal CV score: 0.9926570048309179

Generation 3 - Current best internal CV score: 0.9926570048309179

Generation 4 - Current best internal CV score: 1.0

Generation 5 - Current best internal CV score: 1.0

Generation 6 - Current best internal CV score: 1.0

Generation 7 - Current best internal CV score: 1.0

Generation 8 - Current best internal CV score: 1.0

Generation 9 - Current best internal CV score: 1.0

Generation 10 - Current best internal CV score: 1.0

Generation 11 - Current best internal CV score: 1.0

10.17 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: ExtraTreesClassifier(input_matrix, bootstrap=False, criterion=gini, max_features=0.35000000000000003, min_samples_leaf=1, min_samples_split=17, n_estimators=100)
Best pipeline: Pipeline(steps=[('extratreesclassifier',
                 ExtraTreesClassifier(max_features=0.35000000000000003,
                                      min_samples_split=17,
                                      random_state=123))])
Test Macro F1: 0.9743
Search runtime: 610.68 seconds

Running TPOT: wine | seed 2026

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9936507936507937

Generation 2 - Current best internal CV score: 0.9936507936507937

Generation 3 - Current best internal CV score: 1.0

Generation 4 - Current best internal CV score: 1.0

Generation 5 - Current best internal CV score: 1.0

Generation 6 - Current best internal CV score: 1.0

Generation 7 - Current best internal CV score: 1.0

Generation 8 - Current best internal CV score: 1.0

Generation 9 - Current best internal CV score: 1.0

Generation 10 - Current best internal CV score: 1.0

Generation 11 - Current best internal CV score: 1.0

Generation 12 - Current best internal CV score: 1.0

Generation 13 - Current best internal CV score: 1.0

10.34 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: GradientBoostingClassifier(input_matrix, learning_rate=0.01, max_depth=1, max_features=0.5, min_samples_leaf=6, min_samples_split=10, n_estimators=100, subsample=0.3)
Best pipeline: Pipeline(steps=[('gradientboostingclassifier',
                 GradientBoostingClassifier(learning_rate=0.01, max_depth=1,
                                            max_features=0.5,
                                            min_samples_leaf=6,
                                            min_samples_split=10,
                                            random_state=2026,
                                            subsample=0.3))])
Test Macro F1: 0.9487
Search runtime: 620.96 seconds

Running TPOT: titanic | seed 42

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.7935797584882682

Generation 2 - Current best internal CV score: 0.7935797584882682

Generation 3 - Current best internal CV score: 0.7935797584882682

Generation 4 - Current best internal CV score: 0.7935797584882682

Generation 5 - Current best internal CV score: 0.7975779667230769

Generation 6 - Current best internal CV score: 0.7975779667230769

Generation 7 - Current best internal CV score: 0.7975779667230769

Generation 8 - Current best internal CV score: 0.7984270718778539

10.12 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: RandomForestClassifier(ZeroCount(input_matrix), bootstrap=False, criterion=gini, max_features=0.2, min_samples_leaf=1, min_samples_split=18, n_estimators=100)
Best pipeline: Pipeline(steps=[('zerocount', ZeroCount()),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=False, max_features=0.2,
                                        min_samples_split=18,
                                        random_state=42))])
Test Macro F1: 0.8059
Search runtime: 607.46 seconds

Running TPOT: titanic | seed 123

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.7988493732876467

Generation 2 - Current best internal CV score: 0.8017509510656797

Generation 3 - Current best internal CV score: 0.8017509510656797

Generation 4 - Current best internal CV score: 0.8019448148890351

Generation 5 - Current best internal CV score: 0.8074256116800038

Generation 6 - Current best internal CV score: 0.8074256116800038

Generation 7 - Current best internal CV score: 0.8074256116800038

Generation 8 - Current best internal CV score: 0.8074256116800038

Generation 9 - Current best internal CV score: 0.8093879291987554

10.15 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: RandomForestClassifier(RFE(input_matrix, criterion=entropy, max_features=0.9000000000000001, n_estimators=100, step=0.8500000000000001), bootstrap=False, criterion=entropy, max_features=0.9000000000000001, min_samples_leaf=10, min_samples_split=7, n_estimators=100)
Best pipeline: Pipeline(steps=[('rfe',
                 RFE(estimator=ExtraTreesClassifier(criterion='entropy',
                                                    max_features=0.9000000000000001,
                                                    random_state=123),
                     step=0.8500000000000001)),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=False, criterion='entropy',
                                        max_features=0.9000000000000001,
                                        min_samples_leaf=10,
                                        min_samples_split=7,
                                        random_state=123))])
Test Macro F1: 0.7688
Search runtime: 610.46 seconds

Running TPOT: titanic | seed 2026

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.8003179159953071

Generation 2 - Current best internal CV score: 0.8003179159953071

Generation 3 - Current best internal CV score: 0.8090002200158256

Generation 4 - Current best internal CV score: 0.8090002200158256

Generation 5 - Current best internal CV score: 0.8090002200158256

Generation 6 - Current best internal CV score: 0.8090002200158256

Generation 7 - Current best internal CV score: 0.8090002200158256

Generation 8 - Current best internal CV score: 0.8119583177306078

Generation 9 - Current best internal CV score: 0.8119583177306078

Generation 10 - Current best internal CV score: 0.8119583177306078

10.10 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: RandomForestClassifier(CombineDFs(PolynomialFeatures(XGBClassifier(input_matrix, learning_rate=0.1, max_depth=2, min_child_weight=15, n_estimators=100, n_jobs=1, subsample=0.9500000000000001, verbosity=0), degree=2, include_bias=False, interaction_only=False), SelectFromModel(input_matrix, criterion=gini, max_features=0.3, n_estimators=100, threshold=0.05)), bootstrap=True, criterion=entropy, max_features=0.8, min_samples_leaf=6, min_samples_split=3, n_estimators=100)
Best pipeline: Pipeline(steps=[('featureunion',
                 FeatureUnion(transformer_list=[('pipeline',
                                                 Pipeline(steps=[('stackingestimator',
                                                                  StackingEstimator(estimator=XGBClassifier(base_score=None,
                                                                                                            booster=None,
                                                                                                            callbacks=None,
                                                                                                            colsample_bylevel=None,
                                                                                                            colsample_bynode=None,
                                                                                                            colsample_bytree=None,
                                                                                                            device=None,
                                                                                                            early_stopping_rounds=None,
                                                                                                            enable_categorical=False,
                                                                                                            eval_metric=None,
                                                                                                            feat...
                                                                                                            num_parallel_tree=None, ...))),
                                                                 ('polynomialfeatures',
                                                                  PolynomialFeatures(include_bias=False))])),
                                                ('selectfrommodel',
                                                 SelectFromModel(estimator=ExtraTreesClassifier(max_features=0.3,
                                                                                                random_state=2026),
                                                                 threshold=0.05))])),
                ('randomforestclassifier',
                 RandomForestClassifier(criterion='entropy', max_features=0.8,
                                        min_samples_leaf=6, min_samples_split=3,
                                        random_state=2026))])
Test Macro F1: 0.757
Search runtime: 609.37 seconds

Saved all TPOT results to: C:\Users\souha\Downloads\Human Centered AutoML Thesis\Results\tpot_results.csv

,framework,dataset,seed,best_model,accuracy,precision_macro,recall_macro,f1_macro,search_runtime_seconds,prediction_runtime_seconds,total_runtime_seconds
0,TPOT,breast_cancer,42,"Pipeline(steps=[('stackingestimator',\n ...",0.964912,0.962302,0.962302,0.962302,27812.403932,0.010638,27812.414570
1,TPOT,breast_cancer,123,"Pipeline(steps=[('sgdclassifier',\n ...",0.964912,0.962302,0.962302,0.962302,634.362690,0.001839,634.364528
2,TPOT,breast_cancer,2026,"Pipeline(steps=[('minmaxscaler', MinMaxScaler(...",0.938596,0.929952,0.941468,0.934947,604.675655,0.002386,604.678041
3,TPOT,wine,42,"Pipeline(steps=[('polynomialfeatures', Polynom...",0.972222,0.977778,0.966667,0.970962,601.313673,0.002573,601.316245
4,TPOT,wine,123,"Pipeline(steps=[('extratreesclassifier',\n ...",0.972222,0.974359,0.976190,0.974321,610.675178,0.004923,610.680100
5,TPOT,wine,2026,"Pipeline(steps=[('gradientboostingclassifier',...",0.944444,0.952381,0.952381,0.948718,620.960208,0.002464,620.962672
6,TPOT,titanic,42,"Pipeline(steps=[('zerocount', ZeroCount()),\n ...",0.816794,0.805926,0.805926,0.805926,607.455286,0.009401,607.464687
7,TPOT,titanic,123,"Pipeline(steps=[('rfe',\n RFE(...",0.786260,0.776292,0.764012,0.768799,610.459248,0.007588,610.466836
8,TPOT,titanic,2026,"Pipeline(steps=[('featureunion',\n ...",0.774809,0.763222,0.752840,0.756961,609.366036,0.016183,609.382219

In [4]:
from src.tpot_experiments import run_all_tpot_experiments

tpot_results = run_all_tpot_experiments()

tpot_results

Running TPOT: breast_cancer | seed 42

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9811844295188893

Generation 2 - Current best internal CV score: 0.9812635111075929

Generation 3 - Current best internal CV score: 0.9812635111075929

Generation 4 - Current best internal CV score: 0.9836031442454629

Generation 5 - Current best internal CV score: 0.9836031442454629

Generation 6 - Current best internal CV score: 0.9836054105755505

Generation 7 - Current best internal CV score: 0.9836054105755505

10.18 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: MLPClassifier(MLPClassifier(input_matrix, alpha=0.01, learning_rate_init=1.0), alpha=0.001, learning_rate_init=0.01)

c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(
c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Best pipeline: Pipeline(steps=[('stackingestimator',
                 StackingEstimator(estimator=MLPClassifier(alpha=0.01,
                                                           learning_rate_init=1.0,
                                                           random_state=42))),
                ('mlpclassifier',
                 MLPClassifier(alpha=0.001, learning_rate_init=0.01,
                               random_state=42))])
Test Macro F1: 0.9623
Search runtime: 612.87 seconds

Running TPOT: breast_cancer | seed 123

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9809495283670137

Generation 2 - Current best internal CV score: 0.9809495283670137

Generation 3 - Current best internal CV score: 0.9809495283670137

Generation 4 - Current best internal CV score: 0.9810124720543392

Generation 5 - Current best internal CV score: 0.9810124720543392

Generation 6 - Current best internal CV score: 0.9810124720543392

Generation 7 - Current best internal CV score: 0.9833745745851633

Generation 8 - Current best internal CV score: 0.9833745745851633

Generation 9 - Current best internal CV score: 0.9833745745851633

Generation 10 - Current best internal CV score: 0.9833745745851633

Generation 11 - Current best internal CV score: 0.9833745745851633

Generation 12 - Current best internal CV score: 0.9833745745851633

Generation 13 - Current best internal CV score: 0.9833745745851633

10.05 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: SGDClassifier(BernoulliNB(input_matrix, alpha=100.0, fit_prior=True), alpha=0.001, eta0=0.01, fit_intercept=False, l1_ratio=0.75, learning_rate=constant, loss=hinge, penalty=elasticnet, power_t=50.0)
Best pipeline: Pipeline(steps=[('stackingestimator',
                 StackingEstimator(estimator=BernoulliNB(alpha=100.0))),
                ('sgdclassifier',
                 SGDClassifier(alpha=0.001, eta0=0.01, fit_intercept=False,
                               l1_ratio=0.75, learning_rate='constant',
                               penalty='elasticnet', power_t=50.0,
                               random_state=123))])
Test Macro F1: 0.9619
Search runtime: 602.78 seconds

Running TPOT: breast_cancer | seed 2026

c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(
c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9786368899299933

Generation 2 - Current best internal CV score: 0.9786368899299933

Generation 3 - Current best internal CV score: 0.9786368899299933

Generation 4 - Current best internal CV score: 0.9810084068928507

Generation 5 - Current best internal CV score: 0.9810084068928507

Generation 6 - Current best internal CV score: 0.9811821631888018

Generation 7 - Current best internal CV score: 0.9835140298199366

Generation 8 - Current best internal CV score: 0.9835140298199366

Generation 9 - Current best internal CV score: 0.9835140298199366

Generation 10 - Current best internal CV score: 0.9835140298199366

Generation 11 - Current best internal CV score: 0.9835140298199366

Generation 12 - Current best internal CV score: 0.9835140298199366

10.04 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: MLPClassifier(ZeroCount(StandardScaler(input_matrix)), alpha=0.0001, learning_rate_init=0.001)
Best pipeline: Pipeline(steps=[('standardscaler', StandardScaler()),
                ('zerocount', ZeroCount()),
                ('mlpclassifier', MLPClassifier(random_state=2026))])
Test Macro F1: 0.9623
Search runtime: 605.56 seconds

Running TPOT: wine | seed 42

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.986830674298705

Generation 2 - Current best internal CV score: 0.9926570048309179

Generation 3 - Current best internal CV score: 0.9926570048309179

Generation 4 - Current best internal CV score: 0.9926570048309179

Generation 5 - Current best internal CV score: 0.9926570048309179

10.00 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: MLPClassifier(LinearSVC(input_matrix, C=10.0, dual=False, loss=squared_hinge, penalty=l2, tol=0.1), alpha=0.1, learning_rate_init=0.01)
Best pipeline: Pipeline(steps=[('stackingestimator',
                 StackingEstimator(estimator=LinearSVC(C=10.0, dual=False,
                                                       random_state=42,
                                                       tol=0.1))),
                ('mlpclassifier',
                 MLPClassifier(alpha=0.1, learning_rate_init=0.01,
                               random_state=42))])
Test Macro F1: 0.971
Search runtime: 600.24 seconds

Running TPOT: wine | seed 123

c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearSVC was fitted with feature names
  warnings.warn(

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9926570048309179

Generation 2 - Current best internal CV score: 0.9926570048309179

Generation 3 - Current best internal CV score: 0.9926570048309179

Generation 4 - Current best internal CV score: 1.0

Generation 5 - Current best internal CV score: 1.0

Generation 6 - Current best internal CV score: 1.0

10.16 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: ExtraTreesClassifier(input_matrix, bootstrap=False, criterion=gini, max_features=0.35000000000000003, min_samples_leaf=1, min_samples_split=17, n_estimators=100)
Best pipeline: Pipeline(steps=[('extratreesclassifier',
                 ExtraTreesClassifier(max_features=0.35000000000000003,
                                      min_samples_split=17,
                                      random_state=123))])
Test Macro F1: 0.9743
Search runtime: 609.79 seconds

Running TPOT: wine | seed 2026

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.9936507936507937

Generation 2 - Current best internal CV score: 0.9936507936507937

Generation 3 - Current best internal CV score: 1.0

Generation 4 - Current best internal CV score: 1.0

Generation 5 - Current best internal CV score: 1.0

Generation 6 - Current best internal CV score: 1.0

Generation 7 - Current best internal CV score: 1.0

10.05 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: GradientBoostingClassifier(input_matrix, learning_rate=0.01, max_depth=1, max_features=0.5, min_samples_leaf=6, min_samples_split=10, n_estimators=100, subsample=0.3)
Best pipeline: Pipeline(steps=[('gradientboostingclassifier',
                 GradientBoostingClassifier(learning_rate=0.01, max_depth=1,
                                            max_features=0.5,
                                            min_samples_leaf=6,
                                            min_samples_split=10,
                                            random_state=2026,
                                            subsample=0.3))])
Test Macro F1: 0.9487
Search runtime: 603.26 seconds

Running TPOT: titanic | seed 42

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.7935797584882682

Generation 2 - Current best internal CV score: 0.7935797584882682

Generation 3 - Current best internal CV score: 0.7935797584882682

Generation 4 - Current best internal CV score: 0.7935797584882682

Generation 5 - Current best internal CV score: 0.7975779667230769

10.18 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: RandomForestClassifier(CombineDFs(input_matrix, input_matrix), bootstrap=False, criterion=gini, max_features=0.2, min_samples_leaf=1, min_samples_split=18, n_estimators=100)
Best pipeline: Pipeline(steps=[('featureunion',
                 FeatureUnion(transformer_list=[('functiontransformer-1',
                                                 FunctionTransformer(func=<function copy at 0x0000019BAB396840>)),
                                                ('functiontransformer-2',
                                                 FunctionTransformer(func=<function copy at 0x0000019BAB396840>))])),
                ('randomforestclassifier',
                 RandomForestClassifier(bootstrap=False, max_features=0.2,
                                        min_samples_split=18,
                                        random_state=42))])
Test Macro F1: 0.8052
Search runtime: 611.07 seconds

Running TPOT: titanic | seed 123

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.7988493732876467

Generation 2 - Current best internal CV score: 0.8017509510656797

Generation 3 - Current best internal CV score: 0.8017509510656797

Generation 4 - Current best internal CV score: 0.8019448148890351

Generation 5 - Current best internal CV score: 0.8074256116800038

Generation 6 - Current best internal CV score: 0.8074256116800038

Generation 7 - Current best internal CV score: 0.8074256116800038

Generation 8 - Current best internal CV score: 0.8074256116800038

10.69 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: RandomForestClassifier(ExtraTreesClassifier(input_matrix, bootstrap=False, criterion=gini, max_features=1.0, min_samples_leaf=15, min_samples_split=17, n_estimators=100), bootstrap=True, criterion=gini, max_features=0.8, min_samples_leaf=3, min_samples_split=9, n_estimators=100)

c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(
c:\Users\souha\Downloads\Human Centered AutoML Thesis\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(

Best pipeline: Pipeline(steps=[('stackingestimator',
                 StackingEstimator(estimator=ExtraTreesClassifier(max_features=1.0,
                                                                  min_samples_leaf=15,
                                                                  min_samples_split=17,
                                                                  random_state=123))),
                ('randomforestclassifier',
                 RandomForestClassifier(max_features=0.8, min_samples_leaf=3,
                                        min_samples_split=9,
                                        random_state=123))])
Test Macro F1: 0.7559
Search runtime: 644.26 seconds

Running TPOT: titanic | seed 2026

Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.8003179159953071

Generation 2 - Current best internal CV score: 0.8003179159953071

Generation 3 - Current best internal CV score: 0.8090002200158256

Generation 4 - Current best internal CV score: 0.8090002200158256

Generation 5 - Current best internal CV score: 0.8090002200158256

Generation 6 - Current best internal CV score: 0.8090002200158256

Generation 7 - Current best internal CV score: 0.8090002200158256

Generation 8 - Current best internal CV score: 0.8119583177306078

10.30 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.
WARNING: TPOT may not provide a good pipeline if TPOT is stopped/interrupted in a early generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: RandomForestClassifier(CombineDFs(PolynomialFeatures(XGBClassifier(input_matrix, learning_rate=0.1, max_depth=2, min_child_weight=15, n_estimators=100, n_jobs=1, subsample=0.9500000000000001, verbosity=0), degree=2, include_bias=False, interaction_only=False), SelectFromModel(input_matrix, criterion=gini, max_features=0.3, n_estimators=100, threshold=0.05)), bootstrap=True, criterion=entropy, max_features=0.8, min_samples_leaf=6, min_samples_split=3, n_estimators=100)
Best pipeline: Pipeline(steps=[('featureunion',
                 FeatureUnion(transformer_list=[('pipeline',
                                                 Pipeline(steps=[('stackingestimator',
                                                                  StackingEstimator(estimator=XGBClassifier(base_score=None,
                                                                                                            booster=None,
                                                                                                            callbacks=None,
                                                                                                            colsample_bylevel=None,
                                                                                                            colsample_bynode=None,
                                                                                                            colsample_bytree=None,
                                                                                                            device=None,
                                                                                                            early_stopping_rounds=None,
                                                                                                            enable_categorical=False,
                                                                                                            eval_metric=None,
                                                                                                            feat...
                                                                                                            num_parallel_tree=None, ...))),
                                                                 ('polynomialfeatures',
                                                                  PolynomialFeatures(include_bias=False))])),
                                                ('selectfrommodel',
                                                 SelectFromModel(estimator=ExtraTreesClassifier(max_features=0.3,
                                                                                                random_state=2026),
                                                                 threshold=0.05))])),
                ('randomforestclassifier',
                 RandomForestClassifier(criterion='entropy', max_features=0.8,
                                        min_samples_leaf=6, min_samples_split=3,
                                        random_state=2026))])
Test Macro F1: 0.757
Search runtime: 624.3 seconds

Saved all TPOT results to: C:\Users\souha\Downloads\Human Centered AutoML Thesis\Results\tpot_results.csv

,framework,dataset,seed,best_model,accuracy,precision_macro,recall_macro,f1_macro,search_runtime_seconds,prediction_runtime_seconds,total_runtime_seconds
0,TPOT,breast_cancer,42,"Pipeline(steps=[('stackingestimator',\n ...",0.964912,0.962302,0.962302,0.962302,612.866787,0.005685,612.872472
1,TPOT,breast_cancer,123,"Pipeline(steps=[('stackingestimator',\n ...",0.964912,0.967230,0.957341,0.961911,602.783760,0.006683,602.790444
2,TPOT,breast_cancer,2026,"Pipeline(steps=[('standardscaler', StandardSca...",0.964912,0.962302,0.962302,0.962302,605.559059,0.006841,605.565900
3,TPOT,wine,42,"Pipeline(steps=[('stackingestimator',\n ...",0.972222,0.977778,0.966667,0.970962,600.239251,0.004537,600.243788
4,TPOT,wine,123,"Pipeline(steps=[('extratreesclassifier',\n ...",0.972222,0.974359,0.976190,0.974321,609.793130,0.012919,609.806049
5,TPOT,wine,2026,"Pipeline(steps=[('gradientboostingclassifier',...",0.944444,0.952381,0.952381,0.948718,603.260008,0.002381,603.262389
6,TPOT,titanic,42,"Pipeline(steps=[('featureunion',\n ...",0.816794,0.806434,0.804012,0.805168,611.071446,0.007683,611.079129
7,TPOT,titanic,123,"Pipeline(steps=[('stackingestimator',\n ...",0.774809,0.764012,0.750926,0.755856,644.263586,0.058128,644.321714
8,TPOT,titanic,2026,"Pipeline(steps=[('featureunion',\n ...",0.774809,0.763222,0.752840,0.756961,624.303422,0.045593,624.349015